name: ems
channels:
  - anaconda
  - r
  - conda-forge
dependencies:
  - anaconda::python
  - anaconda::anaconda-navigator
  - anaconda::jupyter
  - r::mro-base
  - r::r-essentials
  - r::r-devtools
  - r::r-dplyr
  - r::r-reticulate
  - r::r-irkernel
  - r::rstudio
  - conda-forge::message-ix
