name: ems
channels:
  - conda-forge
  - anaconda
dependencies:
  - anaconda-navigator
  - mro-base
  - r-essentials
  - r-devtools
  - r-dplyr
  - r-reticulate
  - jupyter
  - jupyterlab
  - r-irkernel
  - message-ix
  - rstudio
