* Setup environment
1. [[https://docs.conda.io/en/latest/miniconda.html][Install Miniconda]] (Python 3.7).
   NOTE: If you use Anaconda instead, and you have problems opening the Anaconda prompt, refer to [[http://docs.anaconda.com/anaconda/user-guide/troubleshooting/#cannot-open-anaconda-prompt-after-installation][this link]].
2. [[https://www.gams.com/latest/docs/UG_MAIN.html#UG_INSTALL][Install GAMS]]. Follow the instructions, plus:
   1. Make sure you add GAMS directory to the [[https://www.java.com/en/download/help/path.xml][PATH environment variable]] (e.g. ticking the corresponding option during the setup). After the installation check that the following works:
      1. open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal;
      2. type
         #+BEGIN_SRC shell
         gams
         #+END_SRC
   2. Rember to add =gamslice.txt= to your GAMS installation path. If this is done correctly you will see a reference to the license after gams is called.
3. Create the =ems= Anaconda environment.
   1. Open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal.
   2. Update conda.
      #+BEGIN_SRC shell
      conda update -n base -c defaults conda
      #+END_SRC
   3. Create a conda environment called =ems=, containing basic R and Python packages, typing:
      #+BEGIN_SRC shell
      conda env create -n ems -c r mro-base r-essentials r-devtools r-dplyr r-reticulate r-irkernel rstudio
      #+END_SRC
   4. Install Message-ix
      #+BEGIN_SRC shell
      conda install -n ems -c conda-forge message-ix
      #+END_SRC
   5. Activate the =ems= environment
      #+BEGIN_SRC shell
      conda activate ems
      #+END_SRC
   6. Install the missing R packages:
      #+BEGIN_SRC shell
      curl -O https://raw.githubusercontent.com/polimi-energy-modelling/ems-conda-setup/master/r-install-packages.R
      Rscript --vanilla r-install-packages.R
      #+END_SRC
   7. If the =conda= command is not recognised, check the PATH environment variable and be sure that the path to =\Anaconda3= as well as =\Anaconda3\Scripts\= are added (as was done previously for GAMS).
      
4. Download MESSAGE tutorials
   1. Open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal.
   2. Activate the =ems= environment, typing:
      #+BEGIN_SRC shell
      conda activate ems
      #+END_SRC
   3. Create and move to a directory where you want to save the tutorials, e.g.: 
      #+BEGIN_SRC shell
      mkdir message
      cd message
      #+END_SRC
   4. Download the tutorials, typing:
      #+BEGIN_SRC shell
      messageix-dl
      #+END_SRC
   5. Test the tutorials in a Jupyter Notebook, typing:
      #+BEGIN_SRC shell
      jupyter notebook
      #+END_SRC

* Launching apps via the terminal
1. Open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal.
2. Activate the =ems= environment, typing:
   #+BEGIN_SRC shell
   conda activate ems
   #+END_SRC
3. Use the following commands to launch a Jupyter Notebook or RStudio:
   #+BEGIN_SRC shell
   jupyter notebook
   rstudio
   #+END_SRC
