* Setup environment
1. [[https://www.anaconda.com/distribution/][Install Anaconda]] (Python 3.7).
2. [[https://www.gams.com/latest/docs/UG_MAIN.html#UG_INSTALL][Install GAMS]]. Follow the instructions, plus:
   1. Make sure you add GAMS directory to the [[https://www.java.com/en/download/help/path.xml][PATH environment variable]] (e.g. ticking the corresponding option during the setup). After the installation check that the following works:
      1. open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal;
      2. type
         #+BEGIN_SRC shell
         gams
         #+END_SRC
   2. Rember to add =gamslice.txt= to your GAMS installation path.
3. Create the =ems= Anaconda environment.
   1. Open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal.
   2. Create a temporary directory and download the needed setup files, typing:
      #+BEGIN_SRC shell
      mkdir ems-conda-setup
      cd ems-conda-setup
      curl -O https://raw.githubusercontent.com/polimi-energy-modelling/ems-conda-setup/master/environment.yml
      curl -O https://raw.githubusercontent.com/polimi-energy-modelling/ems-conda-setup/master/r-install-packages.R      
      #+END_SRC
   3. Create a conda environment called =ems=, containing all the required packages, typing:
      #+BEGIN_SRC shell
      conda env create -f environment.yml
      conda activate ems
      Rscript --vanilla r-install-packages.R
      #+END_SRC
   4. If the =conda= command is not recognised, check PATH environment variables and be sure that the path to \Anaconda3 as well as                \Anaconda3\Scripts\ are added (as was done previously for GAMS).     
      
4. Download MESSAGE tutorials
   1. Open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal.
   2. Activate the =ems= environment, typing:
      #+BEGIN_SRC shell
      conda activate ems
      #+END_SRC
   3. Create and move to a directory where you want to save the tutorials, e.g.: 
      #+BEGIN_SRC shell
      mkdir message
      cd message
      #+END_SRC
   4. Download the tutorials, typing:
      #+BEGIN_SRC shell
      messageix-dl
      #+END_SRC
   5. Test the tutorials in a Jupyter Notebook, typing:
      #+BEGIN_SRC shell
      jupyter notebook
      #+END_SRC

* Launching apps via Anaconda Navigator
1. Launch the [[https://docs.anaconda.com/anaconda/navigator/][Anaconda Navigator]]
2. Make sure the =ems= environment is selected in the "Applications on" dropdown list.
3. Click on an app (e.g. Jupyter Notebook or RStudio).

* Launching apps via the terminal
1. Open an [[https://docs.anaconda.com/anaconda/install/verify-install/#conda][Anaconda prompt]] or terminal.
2. Activate the =ems= environment, typing:
   #+BEGIN_SRC shell
   conda activate ems
   #+END_SRC
3. Use the following commands to launch a Jupyter Notebook or RStudio:
   #+BEGIN_SRC shell
   jupyter notebook
   rstudio
   #+END_SRC
